language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mysql -e 'create database pls_test;'
  - echo "<?php define('MYSQL_HOST', '0.0.0.0'); define('MYSQL_USER', 'travis'); define('MYSQL_PASSWORD', ''); define('MYSQL_DATABASE', 'pls_test');" > ./app/config/pls_config.php
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry php artisan asset:generate --env=testing

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --verbose; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml; fi;'
