language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mysql -e 'create database pls_test;'
  - echo "<?php define('MYSQL_HOST', '0.0.0.0'); define('MYSQL_USER', 'travis'); define('MYSQL_PASSWORD', ''); define('MYSQL_DATABASE', 'pls_test');" > ./app/config/pls_config.php
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry php artisan asset:publish --env=testing
  - travis_retry php artisan migrate -n
  - travis_retry php artisan db:seed -n

script:
  - mkdir -p build/logs
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-clover build/logs/clover.xml; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then php vendor/bin/coveralls -v; fi;'
